In [1]:
import numpy as np
import matplotlib.pyplot as plt
from statistics import mode
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.float_format', lambda x: '%.0f' % x)

excel_bios = pd.read_excel("./../data/Biometricos.xls",sheet_name="Hoja1")

# BIOS

In [21]:
# Leer el archivo Excel
df = pd.read_excel("./../data/movs.xls",sheet_name="Hoja1")

mi_resultado=[]

for i,row in df.iterrows():
    #print(row['BIO'])
    entrega=''
    retiro=''
    found = False
    
    if row['TIPO']=='E':
        entrega=row['FECHA']
        
    if row['TIPO']=='R':
        lastindex=0
        retiro=row['FECHA']
        
        for j,jrow in enumerate(mi_resultado):
            #print('validar: row',row['BIO'],' vs jrow',jrow['BIO'])
            if jrow['BIO']==row['BIO']:
                lastindex=j
                if mi_resultado[j]['RETIRO'] and len(str(mi_resultado[j]['RETIRO'])) > 0: #len(mi_resultado[j]['RETIRO']) > 0: #pd.notna(mi_resultado[j]['RETIRO']): #sin 605 | con 731 | ahora 613
                    #print(mi_resultado[j])
                    #print(pd.notna(mi_resultado[j]['RETIRO']))
                    continue
                mi_resultado[j]['RETIRO']=retiro
                found=True
                #print('-',j)
                
            #print('retiro', lastindex)
    
    if found:
        continue
        
    mi_resultado.append({
            'ENTREGA': entrega,
            'RETIRO': retiro,
            'BIO': row['BIO'],
            'PERSONA': row['PERSONA']
        })
   
df_final = pd.DataFrame(mi_resultado)

#df_final #excel final donde esta unido todas las entregas y retiros de biometricos

light_df_final = pd.isna(df_final['RETIRO'])
df_final_active = df_final[light_df_final]

#df_final_active #todos los biometricos activos en base a los MOVIMIENTOS

C:\Users\Daniel\AppData\Local\Temp\ipykernel_9632\2286623891.py:43: FutureWarning: Inferring datetime64[ns] from data containing strings is deprecated and will be removed in a future version. To retain the old behavior explicitly pass Series(data, dtype=datetime64[ns])
  df_final = pd.DataFrame(mi_resultado)

       ENTREGA     RETIRO          BIO                        PERSONA
0   2024-01-02 2024-03-28  1648I195541       Oficina Micaela Bastidas
1   2024-01-02        NaT  2324I003647          Percy Yupanqui Flores
2   2024-01-02        NaT  2324I003641          Percy Yupanqui Flores
3          NaT 2024-01-02  2150I012772  Leydi Malena Valverde Vasquez
4   2024-01-02 2024-04-19  2324I003632  Leydi Malena Valverde Vasquez
..         ...        ...          ...                            ...
598 2024-08-18        NaT  2224I010333             Kevin Leguia Bravo
599        NaT 2024-08-19  2150I011921                            NaN
600 2024-08-20        NaT  2324I003945                            NaN
601        NaT 2024-08-20  2150I012811                            NaN
602 2024-08-21        NaT  2150I011868                            NaN

[603 rows x 4 columns]

In [22]:
light_df_final = pd.isna(df_final['RETIRO'])
df_final_active = df_final[light_df_final]

df_final_active

       ENTREGA RETIRO          BIO                        PERSONA
1   2024-01-02    NaT  2324I003647          Percy Yupanqui Flores
2   2024-01-02    NaT  2324I003641          Percy Yupanqui Flores
9   2024-01-03    NaT  2224I007877  Yiannena Huayltacayan Salazar
12  2024-01-03    NaT  2324I003628      Alejandrino Campos Alcala
16  2024-01-04    NaT  2324I003640  Roxana Victoria Basurto Cueva
..         ...    ...          ...                            ...
592 2024-08-16    NaT  1647I324094        Nataly Katty Jara Riman
597 2024-08-16    NaT  2324I005445           Oscar Pardo Quintana
598 2024-08-18    NaT  2224I010333             Kevin Leguia Bravo
600 2024-08-20    NaT  2324I003945                            NaN
602 2024-08-21    NaT  2150I011868                            NaN

[220 rows x 4 columns]

In [25]:
light_excel_bios_sac = excel_bios['Tipo'].str.contains('SAC')
excel_bios_sac = excel_bios[light_excel_bios_sac] #np.invert(light_excel_bios_sac)

light_excel_bios_sac_activos = excel_bios_sac['Status'].str.contains('Entregado')
excel_bios_sac_activos = excel_bios_sac[light_excel_bios_sac_activos]

excel_bios_sac_activos

,NÂ°,Biometrico,Tipo,E/R,Fecha E/R,Tipo.1,DNI,Nombres y Apellidos,Zona de Trabajo,PDV / Campo,Encargado,ObservaciÃ³n / Nombre del Retiro,Status
0,1,2150I013629,SAC,E,2024-08-06 00:00:00,DNI,70777300,Mariafernanda Michely Cruz Castillo,Barranca,Campo,T,NaN,Entregado
2,3,2150I013613,SAC,E,2024-08-14 00:00:00,DNI,46357827,Yurico MarÃ­a Prado Mori,Ciudad,Campo,T,NaN,Entregado
4,5,2150I010074,SAC,E,2024-07-08 00:00:00,DNI,45256767,Erika Geraldine Daza Espinoza,Barranca,Campo,E,NaN,Entregado
5,6,2150I010085,SAC,E,2024-08-07 00:00:00,DNI,15628701,Hebert Aduvias Jamanca Cubillas,Paramonga,Pdv,T,NaN,Entregado
6,7,2150I010095,SAC,E,2022-12-22 00:00:00,DNI,43517274,Sara Elizabeth Vento Bernal,Ciudad,Campo,T,NaN,Entregado
...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,394,2324I003717,SAC,E,2024-05-18 00:00:00,DNI,48304424,Edgar Ugarte Cruz,Medio Mundo,Pdv,E,NaN,Entregado
394,395,2324I003739,SAC,E,2024-05-22 00:00:00,CPP,1523250,Francys Jairuska Andrea Machado,Ceres,Campo,T,NaN,Entregado
395,396,2324I003722,SAC,E,2024-05-28 00:00:00,DNI,42687100,Alfredo Freddy Choquehuanca Pacheco,Huacho,Pdv,T,NaN,Entregado
396,397,2347I005263,SAC,E,2024-05-28 00:00:00,DNI,43978213,Julisa Santos Garay,Huaral,Pdv,T,NaN,Entregado
397,398,2324I003716,SAC,E,2024-05-24 00:00:00,DNI,48083717,Angel Joel Chaparro Cardenas,Huaral,Pdv/Campo,T,NaN,Entregado

In [21]:
excel_bios['Status'].unique()

array(['Entregado', 'Perdido/Robado', 'DaÃ±ado', 'En Stock',
       'Oficina TIPTEL', 'En Reparacion'], dtype=object)

In [26]:
conteos = df_final_active['BIO'].value_counts()
conteos.shape

(220,)

In [24]:
df_final_active.shape

(220, 4)

In [ ]:
# necesito 1 que stefani limpie bien la entrega de biometricos para continuar y ver que datos no se repiten entre el excel de
# bios y el excel de movimientos, en caso el excel de bios tenga, significa que esos bios o estÃ¡n perdidos o